-- TribalConnect initial PostgreSQL schema.
-- IDs are generated by Prisma's `uuid()` default at the application boundary.

CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN', 'DEVELOPMENT_OFFICER', 'FIELD_VOLUNTEER', 'FAMILY');
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED');
CREATE TYPE "FamilyStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'DOCUMENT_VERIFICATION', 'FIELD_VISIT', 'APPROVED', 'REJECTED');
CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE "HouseType" AS ENUM ('PUCCA', 'SEMI_PUCCA', 'KUTCHA', 'TEMPORARY');
CREATE TYPE "DocumentType" AS ENUM ('AADHAAR', 'COMMUNITY_CERTIFICATE', 'INCOME_CERTIFICATE', 'RATION_CARD', 'BANK_PASSBOOK', 'PASSPORT_PHOTO', 'HOUSE_PHOTO', 'LAND_DOCUMENT', 'OTHER');
CREATE TYPE "DocumentStatus" AS ENUM ('PENDING', 'VERIFIED', 'REJECTED');
CREATE TYPE "SchemeStatus" AS ENUM ('DRAFT', 'ACTIVE', 'ARCHIVED');
CREATE TYPE "ApplicationStatus" AS ENUM ('RECOMMENDED', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'BENEFIT_RECEIVED');
CREATE TYPE "VisitStatus" AS ENUM ('SCHEDULED', 'COMPLETED', 'MISSED', 'CANCELLED');
CREATE TYPE "WorkflowStage" AS ENUM ('SUBMITTED', 'DOCUMENT_VERIFICATION', 'FIELD_VISIT', 'APPROVAL', 'SCHEME_RECOMMENDATION', 'APPLICATION_SUBMITTED', 'BENEFIT_RECEIVED', 'REJECTED');
CREATE TYPE "NotificationChannel" AS ENUM ('IN_APP', 'SMS', 'WHATSAPP', 'EMAIL');
CREATE TYPE "NotificationStatus" AS ENUM ('QUEUED', 'SENT', 'FAILED', 'READ');
CREATE TYPE "BackupStatus" AS ENUM ('CREATED', 'RESTORED', 'FAILED');

CREATE TABLE "User" (
  "id" TEXT NOT NULL,
  "fullName" TEXT NOT NULL,
  "mobile" TEXT NOT NULL,
  "email" TEXT,
  "role" "Role" NOT NULL,
  "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
  "avatarUrl" TEXT,
  "districtId" TEXT,
  "familyId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "District" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "District_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Block" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "districtId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Block_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Panchayat" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "blockId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Panchayat_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Village" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "hamlet" TEXT,
  "population" INTEGER NOT NULL DEFAULT 0,
  "tribalFamilyCount" INTEGER NOT NULL DEFAULT 0,
  "mapLatitude" DECIMAL(10,7),
  "mapLongitude" DECIMAL(10,7),
  "districtId" TEXT NOT NULL,
  "blockId" TEXT,
  "panchayatId" TEXT,
  "assignedOfficerId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Village_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "DevelopmentCenter" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "address" TEXT NOT NULL,
  "phone" TEXT,
  "email" TEXT,
  "districtId" TEXT NOT NULL,
  "villageId" TEXT,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "DevelopmentCenter_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Family" (
  "id" TEXT NOT NULL,
  "familyCode" TEXT NOT NULL,
  "headName" TEXT NOT NULL,
  "fatherOrHusbandName" TEXT,
  "mobile" TEXT NOT NULL,
  "aadhaarHash" TEXT NOT NULL,
  "aadhaarMasked" TEXT NOT NULL,
  "tribalCommunity" TEXT NOT NULL,
  "casteCertificateNo" TEXT,
  "address" TEXT NOT NULL,
  "panchayatName" TEXT,
  "state" TEXT NOT NULL DEFAULT 'Tamil Nadu',
  "status" "FamilyStatus" NOT NULL DEFAULT 'DRAFT',
  "isWidow" BOOLEAN NOT NULL DEFAULT false,
  "latitude" DECIMAL(10,7),
  "longitude" DECIMAL(10,7),
  "districtId" TEXT NOT NULL,
  "villageId" TEXT NOT NULL,
  "assignedOfficerId" TEXT,
  "submittedAt" TIMESTAMP(3),
  "approvedAt" TIMESTAMP(3),
  "rejectionReason" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Family_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "FamilyMember" (
  "id" TEXT NOT NULL,
  "familyId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "gender" "Gender" NOT NULL,
  "dateOfBirth" TIMESTAMP(3),
  "age" INTEGER,
  "relationship" TEXT NOT NULL,
  "occupation" TEXT,
  "education" TEXT,
  "hasDisability" BOOLEAN NOT NULL DEFAULT false,
  "disabilityType" TEXT,
  "aadhaarHash" TEXT,
  "aadhaarMasked" TEXT,
  "isStudent" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "FamilyMember_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "FamilyIncome" (
  "id" TEXT NOT NULL,
  "familyId" TEXT NOT NULL,
  "annualIncome" DECIMAL(12,2) NOT NULL,
  "primaryOccupation" TEXT,
  "landOwnershipAcres" DECIMAL(10,2),
  "houseType" "HouseType",
  "livestockCount" INTEGER NOT NULL DEFAULT 0,
  "hasBankAccount" BOOLEAN NOT NULL DEFAULT false,
  "bankAccountLast4" TEXT,
  "ifscCode" TEXT,
  "rationCardNumber" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "FamilyIncome_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "FamilyDocument" (
  "id" TEXT NOT NULL,
  "familyId" TEXT NOT NULL,
  "type" "DocumentType" NOT NULL,
  "fileName" TEXT NOT NULL,
  "storageKey" TEXT NOT NULL,
  "mimeType" TEXT NOT NULL,
  "sizeBytes" INTEGER NOT NULL,
  "status" "DocumentStatus" NOT NULL DEFAULT 'PENDING',
  "rejectionNote" TEXT,
  "verifiedById" TEXT,
  "verifiedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "FamilyDocument_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Scheme" (
  "id" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "department" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "benefits" TEXT[] NOT NULL,
  "eligibilitySummary" TEXT,
  "criteria" JSONB NOT NULL DEFAULT '{}',
  "requiredDocuments" TEXT[] NOT NULL,
  "lastDate" TIMESTAMP(3),
  "status" "SchemeStatus" NOT NULL DEFAULT 'DRAFT',
  "applicationLink" TEXT,
  "createdById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Scheme_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "SchemeApplication" (
  "id" TEXT NOT NULL,
  "applicationNumber" TEXT NOT NULL,
  "familyId" TEXT NOT NULL,
  "schemeId" TEXT NOT NULL,
  "status" "ApplicationStatus" NOT NULL DEFAULT 'RECOMMENDED',
  "eligibilitySnapshot" JSONB NOT NULL,
  "notes" TEXT,
  "submittedById" TEXT,
  "submittedAt" TIMESTAMP(3),
  "decidedAt" TIMESTAMP(3),
  "rejectionReason" TEXT,
  "benefitReceivedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "SchemeApplication_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ApplicationStatusEvent" (
  "id" TEXT NOT NULL,
  "applicationId" TEXT NOT NULL,
  "status" "ApplicationStatus" NOT NULL,
  "note" TEXT,
  "actorId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ApplicationStatusEvent_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "FieldVisit" (
  "id" TEXT NOT NULL,
  "familyId" TEXT NOT NULL,
  "villageId" TEXT,
  "volunteerId" TEXT,
  "scheduledAt" TIMESTAMP(3) NOT NULL,
  "completedAt" TIMESTAMP(3),
  "status" "VisitStatus" NOT NULL DEFAULT 'SCHEDULED',
  "purpose" TEXT NOT NULL,
  "notes" TEXT,
  "latitude" DECIMAL(10,7),
  "longitude" DECIMAL(10,7),
  "photoStorageKey" TEXT,
  "clientSyncId" TEXT,
  "syncReceivedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "FieldVisit_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "WorkflowEvent" (
  "id" TEXT NOT NULL,
  "familyId" TEXT NOT NULL,
  "applicationId" TEXT,
  "stage" "WorkflowStage" NOT NULL,
  "title" TEXT NOT NULL,
  "note" TEXT,
  "actorId" TEXT,
  "actorName" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "WorkflowEvent_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Notification" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "channel" "NotificationChannel" NOT NULL DEFAULT 'IN_APP',
  "status" "NotificationStatus" NOT NULL DEFAULT 'QUEUED',
  "readAt" TIMESTAMP(3),
  "metadata" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Announcement" (
  "id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "isPublished" BOOLEAN NOT NULL DEFAULT false,
  "publishedAt" TIMESTAMP(3),
  "expiresAt" TIMESTAMP(3),
  "districtId" TEXT,
  "createdById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Announcement_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "OtpChallenge" (
  "id" TEXT NOT NULL,
  "mobile" TEXT NOT NULL,
  "role" "Role",
  "codeHash" TEXT NOT NULL,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "verifiedAt" TIMESTAMP(3),
  "attempts" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "OtpChallenge_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "AuditLog" (
  "id" TEXT NOT NULL,
  "actorId" TEXT,
  "action" TEXT NOT NULL,
  "entityType" TEXT NOT NULL,
  "entityId" TEXT NOT NULL,
  "metadata" JSONB,
  "ipAddress" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "RefreshToken" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "tokenHash" TEXT NOT NULL,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "revokedAt" TIMESTAMP(3),
  "replacedById" TEXT,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "lastUsedAt" TIMESTAMP(3),
  CONSTRAINT "RefreshToken_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "NotificationPreference" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "sms" BOOLEAN NOT NULL DEFAULT true,
  "whatsapp" BOOLEAN NOT NULL DEFAULT false,
  "email" BOOLEAN NOT NULL DEFAULT true,
  "inApp" BOOLEAN NOT NULL DEFAULT true,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "NotificationPreference_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "UserPreference" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "value" JSONB NOT NULL DEFAULT '{}',
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "UserPreference_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Permission" (
  "id" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "roles" "Role"[] NOT NULL,
  "updatedById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Permission_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "SystemSetting" (
  "key" TEXT NOT NULL,
  "value" JSONB NOT NULL,
  "updatedById" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "SystemSetting_pkey" PRIMARY KEY ("key")
);

CREATE TABLE "BackupRecord" (
  "id" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "status" "BackupStatus" NOT NULL DEFAULT 'CREATED',
  "snapshot" JSONB,
  "summary" JSONB,
  "createdById" TEXT,
  "restoredAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "BackupRecord_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "User_mobile_role_key" ON "User"("mobile", "role");
CREATE UNIQUE INDEX "User_familyId_key" ON "User"("familyId");
CREATE INDEX "User_districtId_idx" ON "User"("districtId");
CREATE INDEX "User_role_status_idx" ON "User"("role", "status");
CREATE UNIQUE INDEX "District_name_key" ON "District"("name");
CREATE UNIQUE INDEX "District_code_key" ON "District"("code");
CREATE UNIQUE INDEX "Block_districtId_name_key" ON "Block"("districtId", "name");
CREATE INDEX "Block_districtId_idx" ON "Block"("districtId");
CREATE UNIQUE INDEX "Panchayat_blockId_name_key" ON "Panchayat"("blockId", "name");
CREATE INDEX "Panchayat_blockId_idx" ON "Panchayat"("blockId");
CREATE UNIQUE INDEX "Village_districtId_name_key" ON "Village"("districtId", "name");
CREATE INDEX "Village_districtId_idx" ON "Village"("districtId");
CREATE INDEX "Village_assignedOfficerId_idx" ON "Village"("assignedOfficerId");
CREATE UNIQUE INDEX "DevelopmentCenter_code_key" ON "DevelopmentCenter"("code");
CREATE INDEX "DevelopmentCenter_districtId_idx" ON "DevelopmentCenter"("districtId");
CREATE UNIQUE INDEX "Family_familyCode_key" ON "Family"("familyCode");
CREATE UNIQUE INDEX "Family_aadhaarHash_key" ON "Family"("aadhaarHash");
CREATE INDEX "Family_districtId_villageId_idx" ON "Family"("districtId", "villageId");
CREATE INDEX "Family_mobile_idx" ON "Family"("mobile");
CREATE INDEX "Family_status_idx" ON "Family"("status");
CREATE INDEX "Family_assignedOfficerId_idx" ON "Family"("assignedOfficerId");
CREATE INDEX "FamilyMember_familyId_idx" ON "FamilyMember"("familyId");
CREATE UNIQUE INDEX "FamilyIncome_familyId_key" ON "FamilyIncome"("familyId");
CREATE INDEX "FamilyDocument_familyId_type_idx" ON "FamilyDocument"("familyId", "type");
CREATE INDEX "FamilyDocument_status_idx" ON "FamilyDocument"("status");
CREATE UNIQUE INDEX "Scheme_code_key" ON "Scheme"("code");
CREATE INDEX "Scheme_status_idx" ON "Scheme"("status");
CREATE INDEX "Scheme_department_idx" ON "Scheme"("department");
CREATE UNIQUE INDEX "SchemeApplication_applicationNumber_key" ON "SchemeApplication"("applicationNumber");
CREATE UNIQUE INDEX "SchemeApplication_familyId_schemeId_key" ON "SchemeApplication"("familyId", "schemeId");
CREATE INDEX "SchemeApplication_schemeId_status_idx" ON "SchemeApplication"("schemeId", "status");
CREATE INDEX "SchemeApplication_familyId_status_idx" ON "SchemeApplication"("familyId", "status");
CREATE INDEX "ApplicationStatusEvent_applicationId_createdAt_idx" ON "ApplicationStatusEvent"("applicationId", "createdAt");
CREATE UNIQUE INDEX "FieldVisit_clientSyncId_key" ON "FieldVisit"("clientSyncId");
CREATE INDEX "FieldVisit_familyId_scheduledAt_idx" ON "FieldVisit"("familyId", "scheduledAt");
CREATE INDEX "FieldVisit_volunteerId_status_idx" ON "FieldVisit"("volunteerId", "status");
CREATE INDEX "WorkflowEvent_familyId_createdAt_idx" ON "WorkflowEvent"("familyId", "createdAt");
CREATE INDEX "WorkflowEvent_applicationId_createdAt_idx" ON "WorkflowEvent"("applicationId", "createdAt");
CREATE INDEX "Notification_userId_status_createdAt_idx" ON "Notification"("userId", "status", "createdAt");
CREATE INDEX "Announcement_isPublished_publishedAt_idx" ON "Announcement"("isPublished", "publishedAt");
CREATE INDEX "OtpChallenge_mobile_role_createdAt_idx" ON "OtpChallenge"("mobile", "role", "createdAt");
CREATE INDEX "AuditLog_entityType_entityId_createdAt_idx" ON "AuditLog"("entityType", "entityId", "createdAt");
CREATE INDEX "AuditLog_actorId_createdAt_idx" ON "AuditLog"("actorId", "createdAt");
CREATE UNIQUE INDEX "RefreshToken_tokenHash_key" ON "RefreshToken"("tokenHash");
CREATE INDEX "RefreshToken_userId_expiresAt_idx" ON "RefreshToken"("userId", "expiresAt");
CREATE INDEX "RefreshToken_expiresAt_idx" ON "RefreshToken"("expiresAt");
CREATE UNIQUE INDEX "NotificationPreference_userId_key" ON "NotificationPreference"("userId");
CREATE UNIQUE INDEX "UserPreference_userId_key" ON "UserPreference"("userId");
CREATE UNIQUE INDEX "Permission_key_key" ON "Permission"("key");
CREATE INDEX "BackupRecord_createdAt_idx" ON "BackupRecord"("createdAt");

ALTER TABLE "User" ADD CONSTRAINT "User_districtId_fkey" FOREIGN KEY ("districtId") REFERENCES "District"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "User" ADD CONSTRAINT "User_familyId_fkey" FOREIGN KEY ("familyId") REFERENCES "Family"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Block" ADD CONSTRAINT "Block_districtId_fkey" FOREIGN KEY ("districtId") REFERENCES "District"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Panchayat" ADD CONSTRAINT "Panchayat_blockId_fkey" FOREIGN KEY ("blockId") REFERENCES "Block"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Village" ADD CONSTRAINT "Village_districtId_fkey" FOREIGN KEY ("districtId") REFERENCES "District"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Village" ADD CONSTRAINT "Village_blockId_fkey" FOREIGN KEY ("blockId") REFERENCES "Block"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Village" ADD CONSTRAINT "Village_panchayatId_fkey" FOREIGN KEY ("panchayatId") REFERENCES "Panchayat"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Village" ADD CONSTRAINT "Village_assignedOfficerId_fkey" FOREIGN KEY ("assignedOfficerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "DevelopmentCenter" ADD CONSTRAINT "DevelopmentCenter_districtId_fkey" FOREIGN KEY ("districtId") REFERENCES "District"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DevelopmentCenter" ADD CONSTRAINT "DevelopmentCenter_villageId_fkey" FOREIGN KEY ("villageId") REFERENCES "Village"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Family" ADD CONSTRAINT "Family_districtId_fkey" FOREIGN KEY ("districtId") REFERENCES "District"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Family" ADD CONSTRAINT "Family_villageId_fkey" FOREIGN KEY ("villageId") REFERENCES "Village"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Family" ADD CONSTRAINT "Family_assignedOfficerId_fkey" FOREIGN KEY ("assignedOfficerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FamilyMember" ADD CONSTRAINT "FamilyMember_familyId_fkey" FOREIGN KEY ("familyId") REFERENCES "Family"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FamilyIncome" ADD CONSTRAINT "FamilyIncome_familyId_fkey" FOREIGN KEY ("familyId") REFERENCES "Family"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FamilyDocument" ADD CONSTRAINT "FamilyDocument_familyId_fkey" FOREIGN KEY ("familyId") REFERENCES "Family"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FamilyDocument" ADD CONSTRAINT "FamilyDocument_verifiedById_fkey" FOREIGN KEY ("verifiedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Scheme" ADD CONSTRAINT "Scheme_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SchemeApplication" ADD CONSTRAINT "SchemeApplication_familyId_fkey" FOREIGN KEY ("familyId") REFERENCES "Family"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SchemeApplication" ADD CONSTRAINT "SchemeApplication_schemeId_fkey" FOREIGN KEY ("schemeId") REFERENCES "Scheme"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SchemeApplication" ADD CONSTRAINT "SchemeApplication_submittedById_fkey" FOREIGN KEY ("submittedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ApplicationStatusEvent" ADD CONSTRAINT "ApplicationStatusEvent_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "SchemeApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ApplicationStatusEvent" ADD CONSTRAINT "ApplicationStatusEvent_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FieldVisit" ADD CONSTRAINT "FieldVisit_familyId_fkey" FOREIGN KEY ("familyId") REFERENCES "Family"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FieldVisit" ADD CONSTRAINT "FieldVisit_villageId_fkey" FOREIGN KEY ("villageId") REFERENCES "Village"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FieldVisit" ADD CONSTRAINT "FieldVisit_volunteerId_fkey" FOREIGN KEY ("volunteerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "WorkflowEvent" ADD CONSTRAINT "WorkflowEvent_familyId_fkey" FOREIGN KEY ("familyId") REFERENCES "Family"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WorkflowEvent" ADD CONSTRAINT "WorkflowEvent_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "SchemeApplication"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WorkflowEvent" ADD CONSTRAINT "WorkflowEvent_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Announcement" ADD CONSTRAINT "Announcement_districtId_fkey" FOREIGN KEY ("districtId") REFERENCES "District"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Announcement" ADD CONSTRAINT "Announcement_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RefreshToken" ADD CONSTRAINT "RefreshToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "NotificationPreference" ADD CONSTRAINT "NotificationPreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserPreference" ADD CONSTRAINT "UserPreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Permission" ADD CONSTRAINT "Permission_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SystemSetting" ADD CONSTRAINT "SystemSetting_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "BackupRecord" ADD CONSTRAINT "BackupRecord_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
